const questions = [
  { question: 'Injure', answer: 'บาดเจ็บ' },
  { question: 'Impolite', answer: 'ไม่สุภาพ' },
  { question: 'Impatient', answer: 'ใจร้อน' },
  { question: 'Assest', answer: 'จับกุม' },
  { question: 'Caused', answer: 'ก่อให้เกิด' },
  { question: 'Fine', answer: 'ค่าปรับ' },
  { question: 'Clause', answer: 'ประโยค' },
  { question: 'Downstair', answer: 'ชั้นล่าง' },
  { question: 'Unusual', answer: 'ผิดปกติ' },
  { question: 'Seem', answer: 'ดูเหมือน' },
  { question: 'Amuse', answer: 'เป็นที่ชอบใจ' },
  { question: 'Terrible', answer: 'น่ากลัว' },
  { question: 'Confuse', answer: 'สับสน' },
  { question: 'Politic', answer: 'การเมือง' },
  { question: 'Complicated', answer: 'ซับซ้อน' },
  { question: 'As good as expected', answer: 'ดีเท่าที่หวัง' },
  { question: 'Rather', answer: 'ค่อนข้าง' },
  { question: 'Ugly', answer: 'น่าเกลียด' },
  { question: 'Expecting', answer: 'ความความหวัง' },
  { question: 'Clam', answer: 'เงียบ, สงบ' },
  { question: 'Which one ?', answer: 'อันไหน' },
  { question: 'Suddenly', answer: 'ทันใดนั้น' },
  { question: 'Complicated', answer: 'ซับซ้อน' },
  { question: 'Getting too', answer: 'เริ่ม' },
  { question: 'Hanging', answer: 'แขวน' },
  { question: 'Horrible', answer: 'น่ากลัว' },
  { question: 'Instructor', answer: 'ผู้สอน' },
  { question: 'Patient', answer: 'ผู้ป่วย' },
  { question: 'Chimney', answer: 'ปล่องไฟ' },
  { question: 'Pork belly', answer: 'หมูสามชั้น ' },
  { question: 'Basil', answer: 'กะเพรา' },
  { question: 'Puddle', answer: 'ของเหลว ' },
  { question: 'Frighten', answer: 'ขู่' },
  { question: 'Disappointed', answer: 'ผิดหวัง' },
  { question: 'Nervours', answer: 'หงุดหงิด' },
  { question: 'Exam', answer: 'การสอบ' },
  { question: 'The lesson', answer: 'บทเรียน' },
  { question: 'Relaxing walk', answer: 'เดินเล่น' },
  { question: 'Speech', answer: 'การพูด' },
  { question: 'Laugh', answer: 'หัวเราะ' },
];

export default questions;
